import type {MDXComponents} from 'mdx/types'
import Image from 'next/image'
import {
    TypographyH1,
    TypographyH2,
    TypographyH3,
    TypographyH4,
    TypographyP,
    TypographyBlockquote,
    TypographyList,
    TypographyOrderedList,
    TypographyListItem,
    TypographyImage,
    ImageRow,
    TypographyLink,
    TypographyInlineCode,
    TypographyTable,
    TypographyTableHead,
    TypographyTableBody,
    TypographyTableRow,
    TypographyTableCell,
    TypographyTableHeaderCell,
    Collapsible,
} from "@/components/ui/typography";

export function useMDXComponents(components: MDXComponents): MDXComponents {
    return {
        Image,
        ImageRow,
        h1: TypographyH1,
        h2: TypographyH2,
        h3: TypographyH3,
        h4: TypographyH4,
        p: TypographyP,
        blockquote: TypographyBlockquote,
        a: TypographyLink,
        ul: TypographyList,
        ol: TypographyOrderedList,
        li: TypographyListItem,
        img: TypographyImage,
        code: TypographyInlineCode,
        table: TypographyTable,
        thead: TypographyTableHead,
        tbody: TypographyTableBody,
        tr: TypographyTableRow,
        td: TypographyTableCell,
        th: TypographyTableHeaderCell,
        Collapsible,
        ...components,
    }
}
